<?php
namespace Wafl\Extensions\Communication\AnswersAdmin\Models\DataModel;
abstract class Question extends \DblEj\Extension\ExtensionDataModel
{
    protected $_questionId;
    protected $_question;
    protected $_details;
    protected $_dateAsked;
    protected $_userId;
    protected $_tags;
    protected $_dateModerated;
    protected $_isApproved;
    protected $_categoryId;

    protected static $extension;

    public function Get_QuestionId()
    {
        return $this->_questionId;
    }
    public function Set_QuestionId($questionId)
    {
		  if ($this->_questionId !== $questionId)
		  {
				$this->_questionId = $questionId;
				$this->ModelChanged("QuestionId");
		  }
    }


    public function Get_Question()
    {
        return $this->_question;
    }
    public function Set_CategoryId($categoryId)
    {
		  if ($this->_categoryId !== $categoryId)
		  {
				$this->_categoryId = $categoryId;
				$this->ModelChanged("CategoryId");
		  }
    }

    public function Get_CategoryId()
    {
        return $this->_categoryId;
    }
    public function Set_Question($question)
    {
		  if ($this->_question !== $question)
		  {
				$this->_question = $question;
				$this->ModelChanged("Question");
		  }
    }

    public function Get_Details()
    {
        return $this->_details;
    }
    public function Set_Details($details)
    {
		  if ($this->_details !== $details)
		  {
				$this->_details = $details;
				$this->ModelChanged("Details");
		  }
    }


    public function Get_DateAsked()
    {
        return $this->_dateAsked;
    }
    public function Set_DateAsked($dateAsked)
    {
		  if ($this->_dateAsked !== $dateAsked)
		  {
				$this->_dateAsked = $dateAsked;
				$this->ModelChanged("DateAsked");
		  }
    }


    public function Get_UserId()
    {
        return $this->_userId;
    }
    public function Set_UserId($userId)
    {
		  if ($this->_userId !== $userId)
		  {
				$this->_userId = $userId;
				$this->ModelChanged("UserId");
		  }
    }


    public function Get_Tags()
    {
        return $this->_tags;
    }
    public function Set_Tags($tags)
    {
		  if ($this->_tags !== $tags)
		  {
				$this->_tags = $tags;
				$this->ModelChanged("Tags");
		  }
    }


    public function Get_DateModerated()
    {
        return $this->_dateModerated;
    }
    public function Set_DateModerated($dateModerated)
    {
		  if ($this->_dateModerated !== $dateModerated)
		  {
				$this->_dateModerated = $dateModerated;
				$this->ModelChanged("DateModerated");
		  }
    }


    public function Get_IsApproved()
    {
        return $this->_isApproved;
    }
    public function Set_IsApproved($isApproved)
    {
		  if ($this->_isApproved !== $isApproved)
		  {
				$this->_isApproved = $isApproved;
				$this->ModelChanged("IsApproved");
		  }
    }

    public static function Get_KeyFieldName()
    {
        return "QuestionId";
    }

	public static function Get_Destination()
	{
		$extension = self::$extension;
        return $extension::Get_TablePrefix()."Questions";
	}

    public static function Set_Extension($extension)
    {
        self::$extension = $extension;
    }

	public static function Get_KeyIsAutoGenerated()
	{
        return true;
	}

	public static function GetFieldDataTypes()
	{
		return array(
			"QuestionId"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"UserId"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"Question"=>\DblEj\Data\Field::DATA_TYPE_STRING,
			"Details"=>\DblEj\Data\Field::DATA_TYPE_STRING,
			"Tags"=>\DblEj\Data\Field::DATA_TYPE_STRING,
			"DateAsked"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"DateModerated"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"IsApproved"=>\DblEj\Data\Field::DATA_TYPE_BOOL,
			"CategoryId"=>\DblEj\Data\Field::DATA_TYPE_INT
		);
	}

}
?>