<?php
namespace Wafl\Extensions\Communication\Answers\Models\DataModel;
abstract class AnswerComment extends \DblEj\Extension\ExtensionDataModel
{
    protected $_answerCommentId;
    protected $_userId;
    protected $_answerId;
    protected $_commentDate;
    protected $_comment;
    protected static $extension;
		
    public function Get_AnswerCommentId()
    {
        return $this->_answerCommentId;
    }
    public function Set_AnswerCommentId($answerCommentId)
    {
		  if ($this->_answerCommentId !== $answerCommentId)
		  {
				$this->_answerCommentId = $answerCommentId;
				$this->ModelChanged("AnswerCommentId");
		  }
    }
            
		
    public function Get_UserId()
    {
        return $this->_userId;
    }
    public function Set_UserId($userId)
    {
		  if ($this->_userId !== $userId)
		  {
				$this->_userId = $userId;
				$this->ModelChanged("UserId");
		  }
    }
    
    public static function Set_Extension($extension)
    {
        self::$extension = $extension;
    }
		
    public function Get_AnswerId()
    {
        return $this->_answerId;
    }
    public function Set_AnswerId($answerId)
    {
		  if ($this->_answerId !== $answerId)
		  {
				$this->_answerId = $answerId;
				$this->ModelChanged("AnswerId");
		  }
    }
            
		
    public function Get_CommentDate()
    {
        return $this->_commentDate;
    }
    public function Set_CommentDate($commentDate)
    {
		  if ($this->_commentDate !== $commentDate)
		  {
				$this->_commentDate = $commentDate;
				$this->ModelChanged("CommentDate");
		  }
    }
            
		
    public function Get_Comment()
    {
        return $this->_comment;
    }
    public function Set_Comment($comment)
    {
		  if ($this->_comment !== $comment)
		  {
				$this->_comment = $comment;
				$this->ModelChanged("Comment");
		  }
    }
            
    public function GetAnswer()
    {
	return \Wafl\Extensions\Communication\Answers\Models\FunctionalModel\Answer::Select("AnswerId = '".$this->Get_AnswerId()."'");
    }

    public function GetUser()
    {
        $userClass = get_class(\Wafl\Core::$CURRENT_USER);
        $userClass::Select("UserId = '".$this->Get_UserId()."'");
    }

    public static function Get_KeyFieldName()
    {
        return "AnswerCommentId";
    }
	public static function Get_Destination()
	{
		$extension = self::$extension;
        return $extension::Get_TablePrefix()."AnswerComments";
	}
	public static function Get_KeyIsAutoGenerated()
	{
        return true;
	}

	public static function GetFieldDataTypes()
	{
		return array
		(
			"AnswerCommentId"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"AnswerId"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"UserId"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"Comment"=>\DblEj\Data\Field::DATA_TYPE_STRING,
			"CommentDate"=>\DblEj\Data\Field::DATA_TYPE_INT
		);
	}	

}
?>