<?php
namespace Wafl\Extensions\Communication\Answers\Models\DataModel;
abstract class Answer extends \DblEj\Extension\ExtensionDataModel
{
    protected $_answerId;
    protected $_questionId;
    protected $_userId;
    protected $_answer;
    protected $_dateAnswered;
    protected $_answerAccepted;
    protected $_upVotes;
    protected $_downVotes;
    protected static $extension;
		
    public function Get_AnswerId()
    {
        return $this->_answerId;
    }
    public function Set_AnswerId($answerId)
    {
		  if ($this->_answerId !== $answerId)
		  {
				$this->_answerId = $answerId;
				$this->ModelChanged("AnswerId");
		  }
    }
            
		
    public function Get_QuestionId()
    {
        return $this->_questionId;
    }
    public function Set_QuestionId($questionId)
    {
		  if ($this->_questionId !== $questionId)
		  {
				$this->_questionId = $questionId;
				$this->ModelChanged("QuestionId");
		  }
    }
            
		
    public function Get_UserId()
    {
        return $this->_userId;
    }
    public function Set_UserId($userId)
    {
		  if ($this->_userId !== $userId)
		  {
				$this->_userId = $userId;
				$this->ModelChanged("UserId");
		  }
    }
            
		
    public function Get_Answer()
    {
        return $this->_answer;
    }
    public function Set_Answer($answer)
    {
		  if ($this->_answer !== $answer)
		  {
				$this->_answer = $answer;
				$this->ModelChanged("Answer");
		  }
    }
            
		
    public function Get_DateAnswered()
    {
        return $this->_dateAnswered;
    }
    public function Set_DateAnswered($dateAnswered)
    {
		  if ($this->_dateAnswered !== $dateAnswered)
		  {
				$this->_dateAnswered = $dateAnswered;
				$this->ModelChanged("DateAnswered");
		  }
    }
            
		
    public function Get_AnswerAccepted()
    {
        return $this->_answerAccepted;
    }
    public function Set_AnswerAccepted($answerAccepted)
    {
		  if ($this->_answerAccepted !== $answerAccepted)
		  {
				$this->_answerAccepted = $answerAccepted;
				$this->ModelChanged("AnswerAccepted");
		  }
    }
            
		
    public function Get_UpVotes()
    {
        return $this->_upVotes;
    }
    public function Set_UpVotes($upVotes)
    {
		  if ($this->_upVotes !== $upVotes)
		  {
				$this->_upVotes = $upVotes;
				$this->ModelChanged("UpVotes");
		  }
    }
            
		
    public function Get_DownVotes()
    {
        return $this->_downVotes;
    }
    public function Set_DownVotes($downVotes)
    {
		  if ($this->_downVotes !== $downVotes)
		  {
				$this->_downVotes = $downVotes;
				$this->ModelChanged("DownVotes");
		  }
    }
            
    public function GetAnswerComments() 
    {
	    return \Wafl\Extensions\Communication\Answers\Models\FunctionalModel\AnswerComment::Select("AnswerId = '".$this->Get_AnswerId()."'");
    }

    public function GetUser()
    {
        $userClass = get_class(\Wafl\Core::$CURRENT_USER);
        return $userClass::Select("UserId = '".$this->Get_UserId()."'");
    }

    public function GetUsersFromMyAnswerComments() 
    {
        $userClass = get_class(\Wafl\Core::$CURRENT_USER);
	    return $userClass::Select("AnswerComments.AnswerId = '".$this->Get_AnswerId()."'",null,null,null,array("AnswerComments"=>"UserId"));
    }

    public static function Get_KeyFieldName()
    {
        return "AnswerId";
    }

	public static function Get_Destination()
	{
		$extension = self::$extension;
        return $extension::Get_TablePrefix()."Answers";
	}

	public static function Get_KeyIsAutoGenerated()
	{
        return true;
	}
    public static function Set_Extension($extension)
    {
        self::$extension = $extension;
    }
	public static function GetFieldDataTypes()
	{
		return array(
			"AnswerId"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"QuestionId"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"UserId"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"Answer"=>\DblEj\Data\Field::DATA_TYPE_STRING,
			"DateAnswered"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"AnswerAccepted"=>\DblEj\Data\Field::DATA_TYPE_BOOL,
			"UpVotes"=>\DblEj\Data\Field::DATA_TYPE_INT,
			"DownVotes"=>\DblEj\Data\Field::DATA_TYPE_INT
		);
	}

}
?>